### ISSUE TITLE
Shyla - Data classification

### ISSUE THREAD

**Issue by d3rp3tt3** [d3rp3tt3/AI-Trivia-ChatBot-Project-3#8]
## Overview
Shyla has done basic exploration and cleaning of the data in her Jupyter notebook. In this task, we will classify the 'Category' column into a smaller number of classifications. We'll do this in order for the chatbot to be able to ask a direct question about specific categories. Currently, there are over 20,000 categories.

**Comment by ShylaTatum** [comment]
used filtered data instead of classification
